### ISSUE TITLE
Chessputzer on the command line error

### ISSUE THREAD

**Issue by viktoras-pal** [metterklume/chessputzer#2]
I tried to use Chessputzer on the command line, but I got an error:

d:\chessputzer-master>putzmain.py -f board09.png
Traceback (most recent call last):
  File "D:\chessputzer-master\putzmain.py", line 238, in <module>
    bd = Board(fname)
  File "D:\chessputzer-master\putzmain.py", line 34, in __init__
    self.squares = splitboardcontour(self.ima)
  File "D:\chessputzer-master\putzlib.py", line 180, in splitboardcontour
    bounds = contourbox(ima)
  File "D:\chessputzer-master\putzlib.py", line 199, in contourbox
    _,contours,_ = cv2.findContours(ee, 1, 2)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by razlupercio** [comment]
Hey @metterklume  great repo! the option to export a bunch of images is great!

I got a similar error like the one of @viktoras-pal:

`mybox:chessputzer raz$ python putzmain.py -f examples/Clipboard03.png 
Traceback (most recent call last):
  File "putzmain.py", line 238, in <module>
    bd = Board(fname)
  File "putzmain.py", line 34, in __init__
    self.squares = splitboardcontour(self.ima)
  File "/Users/raz/chessputzer/putzlib.py", line 180, in splitboardcontour
    bounds = contourbox(ima)
  File "/Users/raz/chessputzer/putzlib.py", line 199, in contourbox
    _,contours,_ = cv2.findContours(ee, 1, 2)
ValueError: need more than 2 values to unpack`

my knowledge with the libs you are using is null so any help solving / debuging this is greatly appreciated

**Comment by semihenser** [comment]
Same issue. :(


EDIT: I found the solution. We have to replace all these "" _ ,contours, _ "" with "" contours,_   "" in in py files. 
This issue is caused by the CV version.
Best luck...
