### ISSUE TITLE
Several error when running from Python

### ISSUE THREAD

**Issue by Navmex** [metterklume/chessputzer#9]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/cesar/Chess/chessputzer/putzmain.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by semihenser** [comment]
You must import computer vision library (CV2) my friend. Google it.
